### PR TITLE
headerDate when header not present, and parsing invalid header

### LINKED ISSUE #16: Improve handling of dates
With the merge of #15 we've introduced an optic `headerDate` which uses `parseTimeOrError`. The use of this function could end up in an exception which is not handled.
Instead, we would like to avoid using a non-total function and perhaps also `parseTimeM` which uses `IO`.

### LINKED ISSUE #46: Cannot add Date header with headerDate
Similar to #40 -- trying to set `headerDate` on a new email results in the header not being added.

### PR DESCRIPTION
**Pull request by singpolyma**
Fixes #46 so that Date header can be added when not already present (with test).

Fixes #16 so that invalid Date header results in Nothing and not bottom (with test).

Allow a slightly more lax version of dates for parsing.

### CODE REVIEW

File: src/Data/RFC5322.hs [hunk 1]
```diff
@@ -233,6 +234,9 @@ special = satisfy isSpecial
 rfc5422DateTimeFormat :: String
 rfc5422DateTimeFormat = "%a, %d %b %Y %T %z"
 
+rfc5422DateTimeFormatLax :: String
+rfc5422DateTimeFormatLax = "%a, %-d %b %Y %-H:%-M:%-S %z"
```
Comment (frasertweedale) [inline src/Data/RFC5322.hs]: To clarify, the `%-H:%-M:%-S` allows the h/m/s without leading zero, correct?

Comment (singpolyma) [reply src/Data/RFC5322.hs]: yes

Comment (frasertweedale) [reply src/Data/RFC5322.hs]: I think `%-d` is correct, but the RFC 5322 (and its predecessors) are clear that H/M/S are all 2DIGIT i.e. elision of leading `0` is prohibited.  Did you encounter this in practice?

Comment (singpolyma) [reply src/Data/RFC5322.hs]: I encountered `%-d` in practice and added the others out of Postel's Law.  Could do only `%-d` for now if that makes you more comfortable until we have an example -- though not sure what the harm is in accepting a date header we can easily know the meaning of.

Comment (frasertweedale) [reply src/Data/RFC5322.hs]: It's fine for now, just good to know you did not encounter the others in practice.  There are several changes that need to be made to date parsing that were not previously (e.g. day of week is options, seconds are optional, and other issues; see https://tools.ietf.org/html/rfc5322#section-3.3).  So I'll accept this change for now because the main behavioural change is a big improvement, and make further changes later.
